name: kimob2b
description: A new Flutter application.

version: 2.16.71+277

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^0.13.3
  equatable: ^2.0.3
  shared_preferences: ^2.0.6
  package_info_plus: ^1.0.4
  url_launcher: ^6.0.3
  local_auth: ^1.1.6
  webview_flutter: ^2.0.10
  # encrypt: ^5.0.0
  share: ^2.0.4
  path_provider: ^2.0.2
  flutter_markdown: ^0.6.2
  html2md: ^1.2.5
  flutter_bloc: ^7.0.1
  uuid: ^3.0.4
  transparent_image: ^2.0.0
  carousel_slider: ^4.0.0
  breakpoint: ^1.2.0
  barcode_scan2: ^4.1.3
  file_picker: ^3.0.3
  cached_network_image: ^3.1.0
  flutter_staggered_grid_view: ^0.4.0
  get_it: ^7.0.0
  font_awesome_flutter: ^9.0.0
  collection: ^1.15.0

  cupertino_icons: ^1.0.3
  decimal: ^1.2.0
  intl: ^0.17.0
  universal_html: ^2.0.8
  syncfusion_flutter_pdfviewer: ^19.3.54-beta
  native_pdf_view: ^5.0.0

  app_links: ^2.2.0

  sentry_flutter: ^6.3.0
  rxdart: ^0.27.3

dependency_overrides:

  font_awesome_flutter:
    path: dependencies/font_awesome_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.6
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3
  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true
  assets:
    - assets/images/no_image.png
    - assets/images/image.png
    - assets/images/cart_badge.png
    - assets/pdf/febos_privacy_en.pdf
    - assets/pdf/febos_privacy_it.pdf
    - assets/pdf/febos_condizioni_generali_en.pdf
    - assets/pdf/febos_condizioni_generali_it.pdf
  fonts:
    - family: KimoIcons
      fonts:
        - asset: lib/src/fonts/fonts/KimoIcons.ttf
    - family: UnitsPerPack
      fonts:
        - asset: lib/src/fonts/packs/fonts/UnitsPerPack.ttf